/*
 * IO Mappings for the PIC24
 */
#ifndef MAPPINGS_H
#define MAPPINGS_H

#define SYSTEM_UART_MODULE 1
#define SYSTEM_UART_TX_MODE 3
#define SYSTEM_UART_RX_PIN 24
/* Change to 22 for FT232R models */
#define SYSTEM_UART_TX_PIN RPOR11bits.RP23R

#define BOOTLOADER_PLATFORM "BLUEBUS_BOOTLOADER_1_1"
/* Defined in milliseconds */
#define BOOTLOADER_TIMEOUT 5000

#define BOOT_MODE_APPLICATION 0
#define BOOT_MODE_BOOTLOADER 1
#define BOOT_MODE_NOW 2

#define CONFIG_BOOTLOADER_MODE 0x04
#define CONFIG_SN_MSB 0x00
#define CONFIG_SN_LSB 0x01

#define BOOTLOADER_BOOTLOADER_START 0x800
#define BOOTLOADER_APPLICATION_START 0x1000
#define BOOTLOADER_APPLICATION_END 0x55700

#define ON_LED_MODE TRISEbits.TRISE0
#define ON_LED LATEbits.LATE0

#define EEPROM_SPI_SDO_MODE 7
#define EEPROM_SPI_SCK_MODE 8
#define EEPROM_CS_PIN PORTDbits.RD8
#define EEPROM_CS_IO_MODE TRISDbits.TRISD8
#define EEPROM_SCK_PIN RPOR8bits.RP16R
#define EEPROM_SDI_PIN 4
#define EEPROM_SDO_PIN RPOR15bits.RP30R

#define UART_SEL_MODE_ENABLE 0
#define UART_SEL_MODE_DISABLE 1
#define UART_SEL_BT_MODE TRISDbits.TRISD4
#define UART_SEL_BT LATDbits.LATD4
#define UART_SEL_MCU_MODE TRISDbits.TRISD2
#define UART_SEL_MCU LATDbits.LATD2

#define NOP_COUNT 768
#endif /* MAPPINGS_H */
