/*
 * IO Mappings for the PIC24
 */
#ifndef IO_MAPPINGS_H
#define IO_MAPPINGS_H
#define IBUS_UART_MODULE 1
#define IBUS_UART_RX_PRIORITY 7
#define IBUS_UART_TX_PRIORITY 5
#define IBUS_UART_RX_PIN 12
#define IBUS_UART_TX_PIN 3
#define IBUS_UART_STATUS PORTDbits.RD3

#define BC127_UART_MODULE 2
#define BC127_UART_RX_PRIORITY 6
#define BC127_UART_TX_PRIORITY 5
#define BC127_UART_RX_PIN 21
#define BC127_UART_TX_PIN 26

#define SYSTEM_UART_MODULE 3
#define SYSTEM_UART_RX_PRIORITY 3
#define SYSTEM_UART_TX_PRIORITY 4
#define SYSTEM_UART_RX_PIN 24
#define SYSTEM_UART_TX_PIN 23

#define EEPROM_SPI_MODULE 1
#define EEPROM_CS_PIN PORTDbits.RD8
#define EEPROM_CS_IO_MODE TRISDbits.TRISD8
#define EEPROM_SCK_PIN 16
#define EEPROM_SDI_PIN 4
#define EEPROM_SDO_PIN 30

#define ON_LED_MODE TRISEbits.TRISE0
#define ON_LED LATEbits.LATE0
#endif /* IO_MAPPINGS_H */
