/*
 * IO Mappings for the PIC24
 */
#ifndef IO_MAPPINGS_H
#define IO_MAPPINGS_H
#define IBUS_UART_MODULE 1
#define IBUS_UART_RX_PRIORITY 7
#define IBUS_UART_TX_PRIORITY 5
#define IBUS_UART_RX_PIN 12
#define IBUS_UART_TX_PIN 3
#define IBUS_UART_STATUS PORTDbits.RD0

#define BC127_UART_MODULE 2
#define BC127_UART_RX_PRIORITY 6
#define BC127_UART_TX_PRIORITY 5
#define BC127_UART_RX_PIN 21
#define BC127_UART_TX_PIN 26

#define SYSTEM_UART_MODULE 3
#define SYSTEM_UART_RX_PRIORITY 3
#define SYSTEM_UART_TX_PRIORITY 4
#define SYSTEM_UART_RX_PIN 23
#define SYSTEM_UART_TX_PIN 24

#define EEPROM_SPI_MODULE 1
#define EEPROM_CS_PIN PORTDbits.RD8
#define EEPROM_CS_IO_MODE TRISDbits.TRISD8
#define EEPROM_SCK_PIN 16
#define EEPROM_SDI_PIN 4
#define EEPROM_SDO_PIN 30

#define I2C2_SDA_MODE TRISFbits.TRISF4
#define I2C2_SDA_DC ODCFbits.ODCF4
#define I2C2_SDA LATFbits.LATF4
#define I2C2_SDA_STATUS PORTFbits.RF4

#define I2C2_SCL_MODE TRISFbits.TRISF5
#define I2C2_SCL_DC ODCFbits.ODCF5
#define I2C2_SCL LATFbits.LATF5
#define I2C2_SCL_STATUS PORTFbits.RF5

#define ON_LED_MODE TRISEbits.TRISE0
#define ON_LED LATEbits.LATE0

#define UART_SEL_MODE TRISDbits.TRISD3
#define UART_SEL_BT 0
#define UART_SEL_MCU 1
#define UART_SEL_MODE TRISDbits.TRISD3
#define UART_SEL LATDbits.LATD3

#define IVT_MODE INTCON2bits.AIVTEN
#define IVT_MODE_APP 1
#define IVT_MODE_BOOT 0
#endif /* IO_MAPPINGS_H */
