/*
 * IO Mappings for the PIC24
 */
#ifndef IO_MAPPINGS_H
#define	IO_MAPPINGS_H

#define BC127_UART_RX_PIN 0
#define BC127_UART_TX_PIN 0
#define BC127_UART_CTS_PIN 0
#define BC127_UART_RTS_PIN 0

#define IBUS_UART_RX_PIN 0
#define IBUS_UART_TX_PIN 0
#define IBUS_UART_CTS_PIN 0
#define IBUS_UART_RTS_PIN 0

#define DEBUGGER_UART_RX_PIN 0
#define DEBUGGER_UART_TX_PIN 0
#define DEBUGGER_UART_CTS_PIN 0
#define DEBUGGER_UART_RTS_PIN 0

#endif	/* IO_MAPPINGS_H */
