/*
 * IO Mappings for the PIC24
 */
#ifndef IO_MAPPINGS_H
#define IO_MAPPINGS_H
#define IBUS_UART_MODULE 1
#define IBUS_UART_RX_PRIORITY 7
#define IBUS_UART_TX_PRIORITY 5
#define IBUS_UART_RX_PIN 38
#define IBUS_UART_TX_PIN 14
#define IBUS_UART_STATUS PORTDbits.RD9

#define BC127_UART_MODULE 2
#define BC127_UART_RX_PRIORITY 6
#define BC127_UART_TX_PRIORITY 5
#define BC127_UART_RX_PIN 32
#define BC127_UART_TX_PIN 31

#define SYSTEM_UART_MODULE 3
#define SYSTEM_UART_RX_PRIORITY 3
#define SYSTEM_UART_TX_PRIORITY 4
#define SYSTEM_UART_RX_PIN 10
#define SYSTEM_UART_TX_PIN 17

#define EEPROM_SPI_MODULE 1
#define EEPROM_CS_PIN PORTGbits.RG0
#define EEPROM_CS_IO_MODE TRISGbits.TRISG0
#define EEPROM_SCK_PIN 21
#define EEPROM_SDI_PIN 26
#define EEPROM_SDO_PIN 19
#define EEPROM_SCK_MODE _ANSG6
#define EEPROM_SDO_MODE _ANSG7
#define EEPROM_SDI_MODE _ANSG8
#endif /* IO_MAPPINGS_H */
